name: CI build

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Gen image tag
      run: echo "TAG_IM=${GITHUB_SHA::7}" >> $GITHUB_ENV


    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REPO }}:${{ env.IMAGE_TAG }} .
        docker tag ${{ secrets.DOCKER_REPO }}:${{ env.TAG_IM }} ${{ secrets.DOCKER_REPO }}:latest
#      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-hello-world:latest .
#    - name: Set image tag
#      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_REPO }}/java-hello:${{ env.IMAGE_TAG }}
